<?php
DirectoryIterator extends SplFileInfo implements SeekableIterator {
	/* 方法 */
	public __construct ( string $path )
	public DirectoryIterator current ( void )
	public int getATime ( void )
	public string getBasename ([ string $suffix ] )
	public int getCTime ( void )
	public string getExtension ( void )
	public string getFilename ( void )
	public int getGroup ( void )
	public int getInode ( void )
	public int getMTime ( void )
	public int getOwner ( void )
	public string getPath ( void )
	public string getPathname ( void )
	public int getPerms ( void )
	public int getSize ( void )
	public string getType ( void )
	public bool isDir ( void )
	public bool isDot ( void )
	public bool isExecutable ( void )
	public bool isFile ( void )
	public bool isLink ( void )
	public bool isReadable ( void )
	public bool isWritable ( void )
	public string key ( void )
	public void next ( void )
	public void rewind ( void )
	public void seek ( int $position )
	public string __toString ( void )
	public bool valid ( void )
}